In [252]:
import pandas as pd

In [253]:
s1=pd.Series([10,20,30,'abc',30])
s1

0     10
1     20
2     30
3    abc
4     30
dtype: object

In [254]:
s1[0]=50
s1

0     50
1     20
2     30
3    abc
4     30
dtype: object

In [255]:
s1

0     50
1     20
2     30
3    abc
4     30
dtype: object

In [256]:
s3=pd.Series([10,20,30,40],index=['a','b','c','d'])
s3

a    10
b    20
c    30
d    40
dtype: int64

In [257]:
s4=pd.Series({'a':10,'b':20,'c':30,'d':40})
s4

a    10
b    20
c    30
d    40
dtype: int64

In [258]:
s3+s4

a    20
b    40
c    60
d    80
dtype: int64

In [259]:
df=pd.DataFrame()
type(df)

pandas.core.frame.DataFrame

In [260]:
df=pd.DataFrame([[101,'Akshay',60000],[102,'sagar',50000],[103,'rohit',70000]],columns=['id','name','salary'])
df

    id    name  salary
0  101  Akshay   60000
1  102   sagar   50000
2  103   rohit   70000

In [261]:
df['id']

0    101
1    102
2    103
Name: id, dtype: int64

In [262]:
df.set_index('id')

       name  salary
id
101  Akshay   60000
102   sagar   50000
103   rohit   70000

In [263]:
df2=pd.DataFrame({'ID':[101,102,103],'Name':['harshal','pratham','dashrath'],'Salary':[60000,70000,45000]})
df2

    ID      Name  Salary
0  101   harshal   60000
1  102   pratham   70000
2  103  dashrath   45000

In [264]:
df3=df.set_index('id')

In [265]:
df3.loc[101]

name      Akshay
salary     60000
Name: 101, dtype: object

In [266]:
df3=df.set_index('id')

In [267]:
df3.loc[101:102]

       name  salary
id
101  Akshay   60000
102   sagar   50000

In [268]:
df3.iloc[0:2]

       name  salary
id
101  Akshay   60000
102   sagar   50000

In [269]:
iris=pd.read_csv("C:/Users/HP/Downloads/Iris.csv")
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [270]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [271]:
iris.tail()

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [272]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [273]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [274]:
iris['Sepal_Length'].mean()

np.float64(5.843333333333334)

In [275]:
iris['Sepal_Length'].agg(['min','max','sum','mean'])

min       4.300000
max       7.900000
sum     876.500000
mean      5.843333
Name: Sepal_Length, dtype: float64

In [276]:
iris['Species'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [277]:
iris['Species'].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [278]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [279]:
iris = pd.read_csv("C:/Users/HP/Downloads/Iris.csv")
iris.drop('Species', axis=1, inplace=True)

In [280]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [281]:
df=pd.read_csv("C:/Users/HP/Downloads/student_10.csv")
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

In [283]:
df['Class']==12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [284]:
df[df['Class']==12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [285]:
df[df['Percentage']>50]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [286]:
df['Student ID']==1008.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Student ID, dtype: bool

In [287]:
df[df['Student ID']==1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [288]:
df.loc[df['Student ID']==1008.0,'Percentage']=92
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        92.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [289]:
df1=pd.DataFrame({'id':[101,102,103],'name':['Akshay','harshal','pratham']})
df1

    id     name
0  101   Akshay
1  102  harshal
2  103  pratham

In [290]:
df2=pd.DataFrame({'dept_id':[1,2,1],'dname':['cse','it','ele']})
df2

   dept_id dname
0        1   cse
1        2    it
2        1   ele

In [291]:
pd.concat([df1,df2],axis=1)

    id     name  dept_id dname
0  101   Akshay        1   cse
1  102  harshal        2    it
2  103  pratham        1   ele

In [292]:
pd.concat([df1,df2])

      id     name  dept_id dname
0  101.0   Akshay      NaN   NaN
1  102.0  harshal      NaN   NaN
2  103.0  pratham      NaN   NaN
0    NaN      NaN      1.0   cse
1    NaN      NaN      2.0    it
2    NaN      NaN      1.0   ele

In [293]:
df3=pd.DataFrame({'id':[1,2,1],'name':['cse','it','ele']})

In [294]:
pd.concat([df1,df3],axis=1)

    id     name  id name
0  101   Akshay   1  cse
1  102  harshal   2   it
2  103  pratham   1  ele

Merge

In [295]:
emp=pd.DataFrame({'id':[101,102,103,104],'name':['Akshay','harshal','pratham','Rohit'],'did':[1,2,4,2]})
emp

    id     name  did
0  101   Akshay    1
1  102  harshal    2
2  103  pratham    4
3  104    Rohit    2

In [296]:
dept=pd.DataFrame({'did':[1,2,3],'dname':['admin','it','sales']})
dept

   did  dname
0    1  admin
1    2     it
2    3  sales

In [297]:
pd.merge(emp,dept,how='inner')

    id     name  did  dname
0  101   Akshay    1  admin
1  102  harshal    2     it
2  104    Rohit    2     it

In [298]:
pd.merge(emp,dept,how='left')

    id     name  did  dname
0  101   Akshay    1  admin
1  102  harshal    2     it
2  103  pratham    4    NaN
3  104    Rohit    2     it

In [299]:
pd.merge(emp,dept,how='right')

      id     name  did  dname
0  101.0   Akshay    1  admin
1  102.0  harshal    2     it
2  104.0    Rohit    2     it
3    NaN      NaN    3  sales

In [300]:
pd.merge(emp,dept,how='outer')

      id     name  did  dname
0  101.0   Akshay    1  admin
1  102.0  harshal    2     it
2  104.0    Rohit    2     it
3    NaN      NaN    3  sales
4  103.0  pratham    4    NaN

#null value handling

In [301]:
df=pd.read_csv("C:/Users/HP/Downloads/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [302]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     object
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), object(1)
memory usage: 532.0+ bytes

In [303]:
df.isnull()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [304]:
df.isnull().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [305]:
df.dropna()   #default axis=0 for row

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [306]:
#numeric - median or mean
#categorical- mode

In [307]:
med_per=df['Percentage'].median()
med_per

np.float64(80.0)

In [308]:
df['Percentage']=df['Percentage'].fillna(med_per)

In [309]:
mean_sh=df['Study hrs'].mean()

In [310]:
df['Study hrs']=df['Study hrs'].fillna(mean_sh)

In [311]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021         NaN     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [312]:
df['Student ID'].interpolate()

0    1001.0
1    1002.0
2    1003.0
3    1004.0
4    1005.0
5    1006.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [313]:
df['Student ID'].bfill()

0    1001.0
1    1002.0
2    1005.0
3    1005.0
4    1005.0
5    1007.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [314]:
df['Student ID'].ffill()

0    1001.0
1    1002.0
2    1002.0
3    1002.0
4    1005.0
5    1005.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [315]:
df['Student ID']=df['Student ID'].interpolate()

In [316]:
df.isnull().sum()

Date          0
Student ID    0
Class         0
Study hrs     0
Percentage    0
dtype: int64

In [319]:
res=df.groupby('Class')

In [320]:
list(res)

[(10,
           Date  Student ID  Class  Study hrs  Percentage
  0  01-07-2021      1001.0     10        2.0        50.0
  1  02-07-2021      1002.0     10        6.0        80.0
  2  03-07-2021      1003.0     10        3.0        60.0),
 (11,
           Date  Student ID  Class  Study hrs  Percentage
  3  06-07-2021      1004.0     11        0.0        80.0
  4  07-07-2021      1005.0     11        4.0        80.0
  5  08-07-2021      1006.0     11       10.0        80.0),
 (12,
           Date  Student ID  Class  Study hrs  Percentage
  6  09-07-2021      1007.0     12      4.000        80.0
  7  10-07-2021      1008.0     12      4.375        90.0
  8  11-07-2021      1009.0     12      4.375        60.0
  9  12-07-2021      1010.0     12      6.000        85.0)]

In [323]:
data=dict(list(res))
data

{10:          Date  Student ID  Class  Study hrs  Percentage
 0  01-07-2021      1001.0     10        2.0        50.0
 1  02-07-2021      1002.0     10        6.0        80.0
 2  03-07-2021      1003.0     10        3.0        60.0,
 11:          Date  Student ID  Class  Study hrs  Percentage
 3  06-07-2021      1004.0     11        0.0        80.0
 4  07-07-2021      1005.0     11        4.0        80.0
 5  08-07-2021      1006.0     11       10.0        80.0,
 12:          Date  Student ID  Class  Study hrs  Percentage
 6  09-07-2021      1007.0     12      4.000        80.0
 7  10-07-2021      1008.0     12      4.375        90.0
 8  11-07-2021      1009.0     12      4.375        60.0
 9  12-07-2021      1010.0     12      6.000        85.0}

In [324]:
data[10]

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1003.0     10        3.0        60.0

In [325]:
rec_10=data[10]

In [326]:
rec_10['Percentage'].mean()

np.float64(63.333333333333336)

In [327]:
rec_10['Study hrs'].sum()

np.float64(11.0)